"""What F&O requires, and the two write paths that make a short line typeable.

The readiness gate decides whether a month can be entered at all, so its rules are worth
holding down: a placeholder is not a value, a customer with no rule requires nothing, and
internal time is never short of anything because it is never entered.

The write paths are held to the same standard as the TODO and task-file ones: a correction
changes the line it names and leaves every other byte -- the file's own prose, its earlier
correction notes, a comment on a field -- exactly as it was.
"""
import io
import os
import shutil
import tempfile
import unittest

import _bootstrap  # noqa: F401
import dashboard
from lib import fno


NODE = (
    "# Widget - AGENTS.md (customer node)\n"
    "\n"
    "## Customer\n"
    "name: Widget\n"
    "status: active\n"
    "language: da\n"
    "\n"
    "## About\n"
    "A stand-in.\n"
)

PROJECT = (
    "# Widget - Portal\n"
    "\n"
    "## Identity\n"
    "type: function\n"
    "status: active\n"
    "fno_code:            # no code yet\n"
    "language: da\n"
    "\n"
    "## Purpose\n"
    "A stand-in project.\n"
)

DAY = (
    "# Timesheet - 2026-09-15 (Tue)\n"
    "\n"
    "Generated by ops/time/rollup.py from heartbeats; reviewed/adjusted at /log.\n"
    "Rounded to 0.25 h, min 0.5 h. Edit this file to correct -- never the heartbeats.\n"
    "\n"
    "| Project | Proj ID | Activity | Task | Hours | Billable |\n"
    "|---|---|---|---|---|---|\n"
    "| customers/Widget/portal | UNSET | - | - | 3.00 | yes |\n"
    "| Dev | INTERNAL-RND | - | - | 1.50 | no |\n"
    "\n"
    "**Billable total:** 3.00 h\n"
    "**Internal total:** 1.50 h\n"
    "\n"
    "Reviewed at /log 2026-09-15: nothing to correct.\n"
)


TASK = (
    "---\n"
    "title: Build the Widget portal\n"
    "project: customers/Widget/portal\n"
    "status: open\n"
    "activity:\n"
    "fno_task: none        # no Azure DevOps work item yet\n"
    "---\n"
    "\n"
    "# Build the Widget portal\n"
    "\n"
    "## Progress\n"
    "- 2026-09-14 - started.\n"
)


class IsUnset(unittest.TestCase):
    """A placeholder is the absence of a value, however it is spelled."""

    def test_placeholders(self):
        for v in ("", "   ", None, "UNSET", "unset", "?", "6013-?", "PENDING", "PENDING code",
                  "none", "None"):
            self.assertTrue(fno.is_unset(v), repr(v))

    def test_real_codes(self):
        for v in ("230-02", "4058-1", "INTERNAL-RND", "222", "CarlRData-557", "Task-72114"):
            self.assertFalse(fno.is_unset(v), repr(v))

    def test_value_or_blank(self):
        # `fno_task: none` is the task-file convention for "no work item yet". It must never
        # be typed into F&O as though it were one.
        self.assertEqual(fno.value_or_blank("none"), "")
        self.assertEqual(fno.value_or_blank(" CarlRData-557 "), "CarlRData-557")


class Norm(unittest.TestCase):

    def test_spelling_variants_meet(self):
        self.assertEqual(fno.norm("Carl Ras"), fno.norm("Carl-Ras"))
        self.assertEqual(fno.norm("Vestforbrænding"), "vestforbraending")

    def test_sheet_typo_is_aliased(self):
        self.assertEqual(fno.norm("Vestforbraeding"), "vestforbraending")

    def test_jtj(self):
        self.assertEqual(fno.norm("JTJ"), fno.norm("JoeAndTheJuice"))


class Rules(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.dir = os.path.join(self.tmp, "customers", "Widget")
        os.makedirs(self.dir)
        self.path = os.path.join(self.dir, "AGENTS.md")

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def write(self, text):
        with io.open(self.path, "w", encoding="utf-8", newline="") as f:
            f.write(text)

    def test_a_node_with_no_rule_has_none(self):
        self.write(NODE)
        self.assertEqual(fno.rules(self.tmp), {})

    def test_requires_is_a_list(self):
        self.write(NODE.replace("language: da",
                                "language: da\nfno_requires: task, activity   # confirmed"))
        r = fno.rules(self.tmp)["widget"]
        self.assertEqual(r["requires"], ["activity", "task"])
        self.assertEqual(r["customer"], "Widget")

    def test_only_an_explicit_no_turns_billing_off(self):
        self.write(NODE.replace("language: da", "language: da\nfno_billable: no"))
        self.assertTrue(fno.rules(self.tmp)["widget"]["no_charge"])
        self.write(NODE.replace("language: da", "language: da\nfno_code: 222"))
        self.assertFalse(fno.rules(self.tmp)["widget"]["no_charge"])


class TaskOverrides(unittest.TestCase):
    """A work-task with its own fno_code is found again from the line's dimensions."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        os.makedirs(os.path.join(self.tmp, "ops", "tasks", "in-progress"))

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def put(self, slug, text):
        p = os.path.join(self.tmp, "ops", "tasks", "in-progress", slug + ".md")
        with io.open(p, "w", encoding="utf-8", newline="") as f:
            f.write(text)

    def test_keyed_on_proj_id_activity_task(self):
        self.put("dv", TASK.replace("activity:\n", "activity: 112744\nfno_code: 230-04\n"
                                    "fno_category: F\n").replace(
                 "fno_task: none        # no Azure DevOps work item yet", "fno_task:"))
        self.assertEqual(fno.task_overrides(self.tmp),
                         {"230-04|112744|": {"slug": "dv", "category": "F"}})

    def test_a_task_without_fno_code_is_absent(self):
        self.put("plain", TASK)
        self.assertEqual(fno.task_overrides(self.tmp), {})


class Missing(unittest.TestCase):

    def row(self, **kw):
        base = {"firma": "PING", "proj_id": "230-02", "activity": "", "fno_task": "",
                "description": ""}
        base.update(kw)
        return base

    def test_ready(self):
        self.assertEqual(fno.missing(self.row(), {"requires": []}), [])

    def test_internal_is_never_short(self):
        self.assertEqual(fno.missing(self.row(firma="INTERNAL", proj_id=""), None), [])

    def test_a_placeholder_proj_id_is_missing(self):
        got = fno.missing(self.row(proj_id="?"), None)
        self.assertEqual([m["field"] for m in got], ["proj_id"])

    def test_no_company(self):
        got = fno.missing(self.row(firma=""), None)
        self.assertEqual([m["field"] for m in got], ["firma"])

    def test_the_customer_rule_decides(self):
        rule = {"requires": ["task"]}
        self.assertEqual([m["field"] for m in fno.missing(self.row(), rule)], ["fno_task"])
        self.assertEqual(fno.missing(self.row(fno_task="CarlRData-557"), rule), [])

    def test_a_task_override_is_not_held_to_the_customer_rule(self):
        # Booked on the task's own fno_code: the customer's rule describes another project.
        rule = {"requires": ["task"]}
        self.assertEqual(fno.missing(self.row(proj_id="230-04", activity="112744",
                                              override=True), rule), [])

    def test_description(self):
        rule = {"requires": ["activity", "description"]}
        got = [m["field"] for m in fno.missing(self.row(), rule)]
        self.assertEqual(got, ["activity", "description"])


class FnoField(unittest.TestCase):
    """The source fix: one field on one AGENTS.md, nothing else touched."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.pdir = os.path.join(self.tmp, "customers", "Widget", "portal")
        os.makedirs(self.pdir)
        self.node = os.path.join(self.tmp, "customers", "Widget", "AGENTS.md")
        self.proj = os.path.join(self.pdir, "AGENTS.md")
        for path, body in ((self.node, NODE), (self.proj, PROJECT)):
            with io.open(path, "w", encoding="utf-8", newline="") as f:
                f.write(body)
        self._root = dashboard.ROOT
        dashboard.ROOT = self.tmp

    def tearDown(self):
        dashboard.ROOT = self._root
        shutil.rmtree(self.tmp, ignore_errors=True)

    def read(self, p):
        with io.open(p, encoding="utf-8", newline="") as f:
            return f.read()

    def test_sets_the_value_and_keeps_the_comment(self):
        ok, msg = dashboard.fno_field("project", "customers/Widget/portal", "fno_code", "901-07")
        self.assertTrue(ok, msg)
        self.assertIn("fno_code: 901-07     # no code yet", self.read(self.proj))

    def test_the_rest_of_the_file_is_untouched(self):
        before = self.read(self.proj)
        dashboard.fno_field("project", "customers/Widget/portal", "fno_code", "901-07")
        after = self.read(self.proj)
        self.assertEqual(before.replace("fno_code:            # no code yet",
                                        "fno_code: 901-07     # no code yet"), after)

    def test_a_field_the_block_lacks_is_appended(self):
        ok, _ = dashboard.fno_field("project", "customers/Widget/portal",
                                    "fno_description", "45394 Lineage documentation")
        self.assertTrue(ok)
        text = self.read(self.proj)
        self.assertIn("fno_description: 45394 Lineage documentation", text)
        self.assertIn("## Purpose\nA stand-in project.\n", text)

    def test_the_customer_node_uses_its_own_block(self):
        ok, _ = dashboard.fno_field("customer", "Widget", "fno_requires", "task")
        self.assertTrue(ok)
        self.assertIn("fno_requires: task", self.read(self.node))

    def test_only_fno_fields(self):
        ok, msg = dashboard.fno_field("project", "customers/Widget/portal", "status", "done")
        self.assertFalse(ok)
        self.assertIn("not an F&O field", msg)

    def test_a_value_cannot_carry_a_newline(self):
        ok, _ = dashboard.fno_field("project", "customers/Widget/portal",
                                    "fno_code", "9\n## Identity\nstatus: gone")
        self.assertFalse(ok)

    def test_a_target_cannot_climb_out(self):
        for bad in ("../../etc", "customers/Widget", "own", ""):
            ok, _ = dashboard.fno_field("project", bad, "fno_code", "1")
            self.assertFalse(ok, bad)


class TimesheetEdit(unittest.TestCase):
    """The row fix: correct one line of a finalized day, the way the file says to."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.month = os.path.join(self.tmp, "timesheet", "2026-09")
        os.makedirs(self.month)
        self.path = os.path.join(self.month, "2026-09-15.md")
        with io.open(self.path, "w", encoding="utf-8", newline="") as f:
            f.write(DAY)
        self._ts = dashboard.rollup.TIMESHEET
        dashboard.rollup.TIMESHEET = os.path.join(self.tmp, "timesheet")

    def tearDown(self):
        dashboard.rollup.TIMESHEET = self._ts
        shutil.rmtree(self.tmp, ignore_errors=True)

    def read(self):
        with io.open(self.path, encoding="utf-8", newline="") as f:
            return f.read()

    ROW = {"project": "customers/Widget/portal", "proj_id": "UNSET",
           "activity": "", "fno_task": ""}

    def test_sets_the_three_dimensions(self):
        ok, msg = dashboard.timesheet_edit(
            "2026-09-15", self.ROW,
            {"proj_id": "901-08", "activity": "600003", "fno_task": "WID-12"})
        self.assertTrue(ok, msg)
        self.assertIn("| customers/Widget/portal | 901-08 | 600003 | WID-12 | 3.00 | yes |",
                      self.read())

    def test_the_other_line_is_untouched(self):
        dashboard.timesheet_edit("2026-09-15", self.ROW, {"proj_id": "901-08"})
        self.assertIn("| Dev | INTERNAL-RND | - | - | 1.50 | no |", self.read())

    def test_the_files_own_note_survives(self):
        dashboard.timesheet_edit("2026-09-15", self.ROW, {"proj_id": "901-08"}, "why")
        text = self.read()
        self.assertIn("Reviewed at /log 2026-09-15: nothing to correct.", text)
        self.assertIn("Corrected from the dashboard", text)
        self.assertIn("why", text)

    def test_hours_are_rounded_and_the_totals_follow(self):
        ok, msg = dashboard.timesheet_edit("2026-09-15", self.ROW, {"hours": 3.4})
        self.assertTrue(ok, msg)
        text = self.read()
        self.assertIn("| 3.50 | yes |", text)
        self.assertIn("**Billable total:** 3.50 h", text)
        self.assertIn("**Internal total:** 1.50 h", text)

    def test_it_still_parses_back(self):
        dashboard.timesheet_edit("2026-09-15", self.ROW,
                                 {"proj_id": "901-08", "fno_task": "WID-12"})
        rows = dashboard.rollup.parse_daily_file("2026-09-15")
        self.assertEqual(len(rows), 2)
        self.assertEqual(rows[0]["proj_id"], "901-08")
        self.assertEqual(rows[0]["fno_task"], "WID-12")
        self.assertEqual(rows[0]["hours"], 3.0)

    def test_an_unfinalized_day_says_so(self):
        ok, msg = dashboard.timesheet_edit("2026-09-16", self.ROW, {"proj_id": "1"})
        self.assertFalse(ok)
        self.assertIn("not finalized", msg)

    def test_a_row_that_moved_is_refused(self):
        ok, msg = dashboard.timesheet_edit(
            "2026-09-15", dict(self.ROW, proj_id="999"), {"activity": "x"})
        self.assertFalse(ok)
        self.assertIn("refresh", msg)
        self.assertEqual(self.read(), DAY)

    def test_a_no_op_writes_nothing(self):
        ok, msg = dashboard.timesheet_edit("2026-09-15", self.ROW, {"proj_id": "UNSET"})
        self.assertFalse(ok)
        self.assertEqual(self.read(), DAY)

    def test_hours_out_of_range(self):
        for bad in (0, -1, 99, "x"):
            ok, _ = dashboard.timesheet_edit("2026-09-15", self.ROW, {"hours": bad})
            self.assertFalse(ok, bad)
        self.assertEqual(self.read(), DAY)

    def test_a_bad_date_never_reaches_the_disk(self):
        for bad in ("", "2026-9-15", "../../../etc/passwd", "2026-09-15.md"):
            ok, _ = dashboard.timesheet_edit(bad, self.ROW, {"proj_id": "1"})
            self.assertFalse(ok, bad)


class TimesheetSplit(unittest.TestCase):
    """One day's line between the work sessions behind it.

    A timesheet day groups by dimension, so three sessions with nothing tagged are one
    line -- and one line takes one F&O task. Splitting it moves hours between lines of
    the same day; it never creates or drops any."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.month = os.path.join(self.tmp, "timesheet", "2026-09")
        os.makedirs(self.month)
        self.path = os.path.join(self.month, "2026-09-15.md")
        with io.open(self.path, "w", encoding="utf-8", newline="") as f:
            f.write(DAY)
        self._ts = dashboard.rollup.TIMESHEET
        self._sl = dashboard.sessionlines.ROOT
        dashboard.rollup.TIMESHEET = os.path.join(self.tmp, "timesheet")
        dashboard.sessionlines.ROOT = self.tmp

    def tearDown(self):
        dashboard.rollup.TIMESHEET = self._ts
        dashboard.sessionlines.ROOT = self._sl
        shutil.rmtree(self.tmp, ignore_errors=True)

    def read(self):
        with io.open(self.path, encoding="utf-8", newline="") as f:
            return f.read()

    ROW = {"project": "customers/Widget/portal", "proj_id": "UNSET",
           "activity": "", "fno_task": ""}

    def parts(self, *specs):
        return [{"session": s, "hours": h, "fno_task": task} for s, h, task in specs]

    def total(self):
        return round(sum(r["hours"] for r in dashboard.rollup.parse_daily_file("2026-09-15")), 2)

    def test_one_session_becomes_its_own_line(self):
        ok, msg = dashboard.timesheet_split(
            "2026-09-15", self.ROW, self.parts(("947f60fa", 0.75, "WID-12")))
        self.assertTrue(ok, msg)
        text = self.read()
        self.assertIn("| customers/Widget/portal | UNSET | - | - | 2.25 | yes |", text)
        self.assertIn("| customers/Widget/portal | UNSET | - | WID-12 | 0.75 | yes |", text)

    def test_the_day_totals_exactly_what_it_did(self):
        dashboard.timesheet_split("2026-09-15", self.ROW,
                                  self.parts(("a1b2c3d4", 1.0, "WID-12"),
                                             ("e5f6a7b8", 0.5, "WID-13")))
        self.assertEqual(self.total(), 4.5)
        self.assertIn("**Billable total:** 3.00 h", self.read())

    def test_claiming_all_of_it_leaves_no_empty_line(self):
        dashboard.timesheet_split("2026-09-15", self.ROW,
                                  self.parts(("a1b2c3d4", 3.0, "WID-12")))
        text = self.read()
        self.assertNotIn("| customers/Widget/portal | UNSET | - | - |", text)
        self.assertIn("| customers/Widget/portal | UNSET | - | WID-12 | 3.00 | yes |", text)
        self.assertEqual(self.total(), 4.5)

    def test_two_sessions_going_to_one_task_are_one_line(self):
        dashboard.timesheet_split("2026-09-15", self.ROW,
                                  self.parts(("a1b2c3d4", 0.5, "WID-12"),
                                             ("e5f6a7b8", 0.75, "WID-12")))
        self.assertIn("| customers/Widget/portal | UNSET | - | WID-12 | 1.25 | yes |",
                      self.read())

    def test_it_folds_into_a_line_the_day_already_has(self):
        dashboard.timesheet_split("2026-09-15", self.ROW,
                                  self.parts(("a1b2c3d4", 0.5, "WID-12")))
        dashboard.timesheet_split("2026-09-15", self.ROW,
                                  self.parts(("e5f6a7b8", 0.25, "WID-12")))
        text = self.read()
        self.assertIn("| customers/Widget/portal | UNSET | - | WID-12 | 0.75 | yes |", text)
        self.assertEqual(text.count("| WID-12 |"), 1)
        self.assertEqual(self.total(), 4.5)

    def test_the_billable_column_is_inherited(self):
        dashboard.timesheet_split(
            "2026-09-15", {"project": "Dev", "proj_id": "INTERNAL-RND",
                           "activity": "", "fno_task": ""},
            self.parts(("a1b2c3d4", 0.5, "DEV-1")))
        self.assertIn("| Dev | INTERNAL-RND | - | DEV-1 | 0.50 | no |", self.read())
        self.assertIn("**Internal total:** 1.50 h", self.read())

    def test_more_hours_than_the_line_has(self):
        ok, msg = dashboard.timesheet_split("2026-09-15", self.ROW,
                                            self.parts(("a1b2c3d4", 4.0, "WID-12")))
        self.assertFalse(ok)
        self.assertIn("more than the line has", msg)
        self.assertEqual(self.read(), DAY)

    def test_a_part_going_where_the_line_already_is(self):
        ok, msg = dashboard.timesheet_split("2026-09-15", self.ROW,
                                            self.parts(("a1b2c3d4", 0.5, "")))
        self.assertFalse(ok)
        self.assertEqual(self.read(), DAY)

    def test_every_session_lands_on_the_register(self):
        dashboard.timesheet_split("2026-09-15", self.ROW,
                                  self.parts(("a1b2c3d4", 0.5, "WID-12"),
                                             ("e5f6a7b8", 0.5, "WID-13")), "three sessions")
        got = dashboard.sessionlines.assigned(self.tmp)
        self.assertEqual(got[("2026-09-15", "a1b2c3d4", "customers/widget/portal")],
                         {"activity": "", "fno_task": "WID-12"})
        self.assertEqual(got[("2026-09-15", "e5f6a7b8", "customers/widget/portal")],
                         {"activity": "", "fno_task": "WID-13"})

    def test_nothing_is_registered_when_nothing_moved(self):
        dashboard.timesheet_split("2026-09-15", self.ROW,
                                  self.parts(("a1b2c3d4", 9.0, "WID-12")))
        self.assertEqual(dashboard.sessionlines.entries(self.tmp), [])

    def test_a_part_with_no_session_still_splits(self):
        # The evidence is a convenience; the hours are the point.
        ok, msg = dashboard.timesheet_split(
            "2026-09-15", self.ROW, [{"hours": 0.5, "fno_task": "WID-12"}])
        self.assertTrue(ok, msg)
        self.assertEqual(dashboard.sessionlines.entries(self.tmp), [])

    def test_an_activity_only_split(self):
        ok, msg = dashboard.timesheet_split(
            "2026-09-15", self.ROW,
            [{"session": "a1b2c3d4", "hours": 0.5, "activity": "400760"}])
        self.assertTrue(ok, msg)
        self.assertIn("| customers/Widget/portal | UNSET | 400760 | - | 0.50 | yes |",
                      self.read())

    def test_the_file_says_what_was_split(self):
        dashboard.timesheet_split("2026-09-15", self.ROW,
                                  self.parts(("a1b2c3d4", 0.5, "WID-12")), "the cluster error")
        text = self.read()
        self.assertIn("Split from the dashboard", text)
        self.assertIn("0.50 h -> WID-12", text)
        self.assertIn("the cluster error", text)
        self.assertIn("Reviewed at /log 2026-09-15: nothing to correct.", text)

    def test_an_unfinalized_day_says_so(self):
        ok, msg = dashboard.timesheet_split("2026-09-16", self.ROW,
                                            self.parts(("a1b2c3d4", 0.5, "WID-12")))
        self.assertFalse(ok)
        self.assertIn("not finalized", msg)

    def test_a_row_that_moved_is_refused(self):
        ok, msg = dashboard.timesheet_split("2026-09-15", dict(self.ROW, proj_id="999"),
                                            self.parts(("a1b2c3d4", 0.5, "WID-12")))
        self.assertFalse(ok)
        self.assertIn("refresh", msg)
        self.assertEqual(self.read(), DAY)

    def test_what_it_refuses_outright(self):
        for date, parts in (("", self.parts(("a1b2c3d4", 0.5, "WID-12"))),
                            ("2026-9-15", self.parts(("a1b2c3d4", 0.5, "WID-12"))),
                            ("2026-09-15", []),
                            ("2026-09-15", self.parts(("a1b2c3d4", 0, "WID-12"))),
                            ("2026-09-15", self.parts(("a1b2c3d4", "x", "WID-12"))),
                            ("2026-09-15", self.parts(("a1b2c3d4", 0.5, "WID|12")))):
            ok, _ = dashboard.timesheet_split(date, self.ROW, parts)
            self.assertFalse(ok, (date, parts))
        self.assertEqual(self.read(), DAY)

    def test_hours_are_rounded_to_the_quarter(self):
        dashboard.timesheet_split("2026-09-15", self.ROW,
                                  self.parts(("a1b2c3d4", 0.6, "WID-12")))
        self.assertIn("| WID-12 | 0.50 | yes |", self.read())
        self.assertEqual(self.total(), 4.5)


class EntryRows(unittest.TestCase):
    """What the row shows is resolved; what the file holds is what an edit must name."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self._root, self._comp, self._rules = dashboard.ROOT, dashboard.read_companies, fno.rules
        dashboard.ROOT = self.tmp
        dashboard.read_companies = lambda: [
            {"firma": "PING", "kunde": "Widget", "key": "widget",
             "projektnr": "230-02", "aktivitet": "600003", "task_note": ""}]
        dashboard.fno.rules = lambda root=None: {
            "widget": {"customer": "Widget", "firma": "", "proj_id": "", "activity": "",
                       "description": "", "requires": ["task"], "no_charge": False,
                       "path": ""}}

    def tearDown(self):
        dashboard.ROOT, dashboard.read_companies = self._root, self._comp
        dashboard.fno.rules = self._rules
        shutil.rmtree(self.tmp, ignore_errors=True)

    def entry(self, **kw):
        base = {"date": "2026-09-15", "project": "customers/Widget/portal", "proj_id": "UNSET",
                "activity": "", "fno_task": "", "hours": 3.0, "billable": True, "live": False}
        base.update(kw)
        return base

    def build(self, entries):
        out = dashboard.collect_entry(entries, ["Widget"], "2026-09-21")
        return {r["date"] + r["project"]: r for r in out["rows"]}, out

    def test_the_sheet_fills_a_gap_and_the_file_value_travels_with_it(self):
        rows, _ = self.build([self.entry()])
        r = rows["2026-09-15customers/Widget/portal"]
        self.assertEqual(r["proj_id"], "230-02")       # what you would type
        self.assertTrue(r["from_sheet"])
        self.assertEqual(r["ws_proj_id"], "UNSET")     # what the day file holds
        self.assertEqual(r["activity"], "600003")
        self.assertEqual(r["ws_activity"], "")

    def test_a_placeholder_in_the_sheet_is_not_a_conflict(self):
        dashboard.read_companies = lambda: [
            {"firma": "Power", "kunde": "Widget", "key": "widget",
             "projektnr": "?", "aktivitet": "", "task_note": ""}]
        rows, _ = self.build([self.entry(proj_id="4058-1")])
        r = rows["2026-09-15customers/Widget/portal"]
        self.assertFalse(r["conflict"])
        self.assertEqual(r["proj_id"], "4058-1")

    def test_a_real_disagreement_is_flagged_and_never_resolved(self):
        rows, _ = self.build([self.entry(proj_id="999-99")])
        r = rows["2026-09-15customers/Widget/portal"]
        self.assertTrue(r["conflict"])
        self.assertEqual(r["proj_id"], "999-99")       # the workspace wins, visibly
        self.assertEqual(r["xl_proj_id"], "230-02")

    def test_the_customer_rule_reaches_the_row(self):
        rows, out = self.build([self.entry()])
        r = rows["2026-09-15customers/Widget/portal"]
        self.assertEqual(r["requires"], ["task"])
        self.assertEqual([m["field"] for m in r["missing"]], ["fno_task"])
        self.assertEqual(len(out["short"]), 1)

    def test_two_file_lines_folding_into_one_row_are_ambiguous(self):
        rows, _ = self.build([self.entry(), self.entry(proj_id="", hours=1.0)])
        r = rows["2026-09-15customers/Widget/portal"]
        self.assertTrue(r["ambiguous"])
        self.assertEqual(r["hours"], 4.0)

    def test_one_line_is_not(self):
        rows, _ = self.build([self.entry()])
        self.assertFalse(rows["2026-09-15customers/Widget/portal"]["ambiguous"])

    def test_internal_time_is_never_short(self):
        rows, _ = self.build([self.entry(project="Dev", proj_id="INTERNAL-RND")])
        r = rows["2026-09-15Dev"]
        self.assertEqual(r["firma"], "INTERNAL")
        self.assertEqual(r["missing"], [])


class SetDims(unittest.TestCase):
    """A task lends its two sub-dimensions to every line tagged with it, so setting them
    there is the durable fix -- and, for a day still accruing, the only one."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        os.makedirs(os.path.join(self.tmp, "ops", "tasks", "open"))
        self.path = os.path.join(self.tmp, "ops", "tasks", "open",
                                 "2026-09-14-widget-portal-build.md")
        with io.open(self.path, "w", encoding="utf-8", newline="") as f:
            f.write(TASK)
        self._root = dashboard.ROOT
        dashboard.ROOT = self.tmp

    def tearDown(self):
        dashboard.ROOT = self._root
        shutil.rmtree(self.tmp, ignore_errors=True)

    def read(self):
        with io.open(self.path, encoding="utf-8", newline="") as f:
            return f.read()

    def set(self, **kw):
        return dashboard.task_mutate("2026-09-14-widget-portal-build", "set-dims", **kw)

    def test_sets_the_task(self):
        ok, msg = self.set(fno_task="WID-99")
        self.assertTrue(ok, msg)
        self.assertIn("fno_task: WID-99", self.read())

    def test_sets_the_activity_alone(self):
        # The Aeven shape: activities exist, tasks do not, so the activity has to be
        # settable without inventing a task alongside it.
        ok, msg = self.set(activity="600003")
        self.assertTrue(ok, msg)
        self.assertIn("activity: 600003", self.read())
        self.assertIn("fno_task: none", self.read())

    def test_a_field_not_sent_is_left_alone(self):
        self.set(fno_task="WID-99")
        self.set(activity="600003")
        text = self.read()
        self.assertIn("fno_task: WID-99", text)
        self.assertIn("activity: 600003", text)

    def test_nothing_sent(self):
        ok, msg = self.set()
        self.assertFalse(ok)
        self.assertEqual(self.read(), TASK)

    def test_the_body_and_the_other_fields_survive(self):
        self.set(fno_task="WID-99")
        text = self.read()
        self.assertIn("project: customers/Widget/portal\n", text)
        self.assertIn("## Progress\n- 2026-09-14 - started.\n", text)

    def test_a_value_cannot_carry_a_newline(self):
        ok, _ = self.set(fno_task="WID-99\nstatus: done")
        self.assertFalse(ok)
        self.assertEqual(self.read(), TASK)

    def test_an_unknown_task(self):
        ok, _ = dashboard.task_mutate("no-such-task", "set-dims", fno_task="X")
        self.assertFalse(ok)


class LineEndings(unittest.TestCase):
    """A write puts the endings back as it found them.

    The substrate is not uniform: task files and AGENTS.md are LF, the timesheet days and
    TODO.md are CRLF because rollup.py writes them in text mode on Windows. Flipping either
    turns a one-line correction into a whole-file diff, which is what makes the correction
    unreviewable -- the same standard `todo_mutate` was held to.
    """

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        os.makedirs(os.path.join(self.tmp, "ops", "tasks", "open"))
        os.makedirs(os.path.join(self.tmp, "customers", "Widget", "portal"))
        os.makedirs(os.path.join(self.tmp, "timesheet", "2026-09"))
        self.task = os.path.join(self.tmp, "ops", "tasks", "open",
                                 "2026-09-14-widget-portal-build.md")
        self.proj = os.path.join(self.tmp, "customers", "Widget", "portal", "AGENTS.md")
        self.day = os.path.join(self.tmp, "timesheet", "2026-09", "2026-09-15.md")
        self._root, self._ts = dashboard.ROOT, dashboard.rollup.TIMESHEET
        dashboard.ROOT = self.tmp
        dashboard.rollup.TIMESHEET = os.path.join(self.tmp, "timesheet")

    def tearDown(self):
        dashboard.ROOT, dashboard.rollup.TIMESHEET = self._root, self._ts
        shutil.rmtree(self.tmp, ignore_errors=True)

    def put(self, path, text, crlf):
        with io.open(path, "wb") as f:
            f.write((text.replace("\n", "\r\n") if crlf else text).encode("utf-8"))

    def endings(self, path):
        with io.open(path, "rb") as f:
            raw = f.read()
        crlf, lf = raw.count(b"\r\n"), raw.count(b"\n")
        return "crlf" if crlf and crlf == lf else "lf" if not crlf else "mixed"

    def run_all(self, crlf):
        want = "crlf" if crlf else "lf"
        self.put(self.task, TASK, crlf)
        self.put(self.proj, PROJECT, crlf)
        self.put(self.day, DAY, crlf)

        ok, msg = dashboard.task_mutate("2026-09-14-widget-portal-build", "set-dims",
                                        fno_task="WID-99")
        self.assertTrue(ok, msg)
        self.assertEqual(self.endings(self.task), want, "task file")

        ok, msg = dashboard.task_mutate("2026-09-14-widget-portal-build", "comment",
                                        text="a note")
        self.assertTrue(ok, msg)
        self.assertEqual(self.endings(self.task), want, "task file after a note")

        ok, msg = dashboard.fno_field("project", "customers/Widget/portal",
                                      "fno_code", "901-08")
        self.assertTrue(ok, msg)
        self.assertEqual(self.endings(self.proj), want, "project AGENTS.md")

        ok, msg = dashboard.timesheet_edit(
            "2026-09-15",
            {"project": "customers/Widget/portal", "proj_id": "UNSET",
             "activity": "", "fno_task": ""},
            {"proj_id": "901-08"})
        self.assertTrue(ok, msg)
        self.assertEqual(self.endings(self.day), want, "timesheet day")

    def test_an_lf_file_stays_lf(self):
        self.run_all(False)

    def test_a_crlf_file_stays_crlf(self):
        # This is the real shape of ops/time/timesheet/*.md, and the case where a rebuilt
        # table would otherwise land LF inside a CRLF file.
        self.run_all(True)


class Workbook(unittest.TestCase):
    """The sheet is the other way into F&O, so it has to be a real workbook."""

    ROWS = [{"date": "2026-09-18", "firma": "PING", "customer": "Widget",
             "project": "customers/Widget/portal", "proj_id": "230-02", "activity": "",
             "fno_task": "WID-1", "hours": 2.25, "missing": []},
            {"date": "2026-09-18", "firma": "PING", "customer": "Other",
             "project": "customers/Other/x", "proj_id": "222", "activity": "111749",
             "fno_task": "", "hours": 1.5, "no_charge": True,
             "missing": [{"label": "Task"}]}]

    def sheet(self, rows, **kw):
        req = {"name": "w38", "title": "2026-W38", "rows": rows}
        req.update(kw)
        name, body = dashboard.entry_workbook(req)
        return name, body

    def test_it_is_a_zip_with_the_parts_excel_needs(self):
        import zipfile
        name, body = self.sheet(self.ROWS)
        self.assertEqual(name, "w38.xlsx")
        z = zipfile.ZipFile(io.BytesIO(body))
        for part in ("[Content_Types].xml", "_rels/.rels", "xl/workbook.xml",
                     "xl/_rels/workbook.xml.rels", "xl/worksheets/sheet1.xml"):
            self.assertIn(part, z.namelist())

    def test_hours_are_numbers_and_text_is_escaped(self):
        import zipfile
        rows = [dict(self.ROWS[0], customer="A & B <ltd>")]
        _, body = self.sheet(rows)
        xml = zipfile.ZipFile(io.BytesIO(body)).read("xl/worksheets/sheet1.xml").decode("utf-8")
        self.assertIn("<v>2.25</v>", xml)
        self.assertIn("A &amp; B &lt;ltd&gt;", xml)

    def test_a_short_line_carries_why(self):
        import zipfile
        _, body = self.sheet(self.ROWS)
        xml = zipfile.ZipFile(io.BytesIO(body)).read("xl/worksheets/sheet1.xml").decode("utf-8")
        self.assertIn("No charge", xml)
        self.assertIn(">Task<", xml)

    def test_the_filename_cannot_escape(self):
        name, _ = self.sheet(self.ROWS, name="../../evil path")
        self.assertEqual(name, "evil-path.xlsx")

    def test_nothing_to_export(self):
        name, msg = dashboard.entry_workbook({"rows": []})
        self.assertIsNone(name)


if __name__ == "__main__":
    unittest.main()
