"""Moving a line off the invoice, and saying a line is not to be registered.

Not all work for a customer can be invoiced -- registering the time itself, fixing the
setup, the dashboard. Two answers, often used together: move the line to `Dev`, an `own/`
project or the customer node, and/or set its `Billable` column to `no` so the entry page
leaves it out of the F&O blocks while the hours stay visible against that client.

The direction is the safety rule. Off a customer is always allowed -- it reduces what is
invoiced. Onto a customer from Dev or own/ is the direction that over-bills and stays a
deliberate one-line call (ops/time/README.md sec.2). Customer to customer is refused
outright: that is two invoices wrong at once.
"""
import io
import os
import shutil
import tempfile
import unittest

import _bootstrap  # noqa: F401
import dashboard


DAY = (
    "# Timesheet - 2026-09-15 (Tue)\n"
    "\n"
    "Generated by ops/time/rollup.py from heartbeats; reviewed/adjusted at /log.\n"
    "\n"
    "| Project | Proj ID | Activity | Task | Hours | Billable |\n"
    "|---|---|---|---|---|---|\n"
    "| customers/Widget/portal | 901-08 | - | WID-1 | 3.00 | yes |\n"
    "| customers/Widget/portal | 901-08 | - | - | 1.00 | yes |\n"
    "| Dev | INTERNAL-RND | - | - | 1.50 | no |\n"
    "\n"
    "**Billable total:** 4.00 h\n"
    "**Internal total:** 1.50 h\n"
    "\n"
    "Reviewed at /log 2026-09-15: nothing to correct.\n"
)

LINE = {"project": "customers/Widget/portal", "proj_id": "901-08",
        "activity": "", "fno_task": "WID-1"}


class Reassign(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        for rel in (("customers", "Widget", "portal"), ("customers", "Other", "thing"),
                    ("own", "MetaAtomic")):
            d = os.path.join(self.tmp, *rel)
            os.makedirs(d)
            with io.open(os.path.join(d, "CLAUDE.md"), "w", encoding="utf-8") as f:
                f.write("# x\n\n## Identity\nfno_code:\n")
        os.makedirs(os.path.join(self.tmp, "timesheet", "2026-09"))
        self.path = os.path.join(self.tmp, "timesheet", "2026-09", "2026-09-15.md")
        with io.open(self.path, "w", encoding="utf-8", newline="") as f:
            f.write(DAY)
        self._root, self._ts = dashboard.ROOT, dashboard.rollup.TIMESHEET
        self._dw, self._vd = dashboard.rollup.DEV_WORKSPACE, dashboard.VALUE
        dashboard.ROOT = dashboard.rollup.DEV_WORKSPACE = self.tmp
        dashboard.rollup.TIMESHEET = os.path.join(self.tmp, "timesheet")
        dashboard.VALUE = os.path.join(self.tmp, "value")
        self._mm = dashboard.measuremoves.ROOT
        dashboard.measuremoves.ROOT = self.tmp

    def tearDown(self):
        dashboard.ROOT, dashboard.rollup.TIMESHEET = self._root, self._ts
        dashboard.rollup.DEV_WORKSPACE, dashboard.VALUE = self._dw, self._vd
        dashboard.measuremoves.ROOT = self._mm
        shutil.rmtree(self.tmp, ignore_errors=True)

    def read(self):
        with io.open(self.path, encoding="utf-8", newline="") as f:
            return f.read()

    def rows(self):
        return dashboard.rollup.parse_daily_file("2026-09-15")

    def find(self, project, task=None):
        return [r for r in self.rows()
                if r["project"] == project and (task is None or r["fno_task"] == task)]

    # ---- the measurement follows the hours

    def test_a_move_writes_the_measure_moves_row(self):
        ok, _ = dashboard.reassign("2026-09-15", LINE, "own/MetaAtomic")
        self.assertTrue(ok)
        got = dashboard.measuremoves.entries(self.tmp)
        self.assertEqual(len(got), 1)
        self.assertEqual((got[0]["from"], got[0]["to"]),
                         ("customers/Widget/portal", "own/MetaAtomic"))
        # the task is a customer dimension; it does not travel onto own/
        self.assertEqual(got[0]["tasks"], [])

    def test_a_move_inside_the_customer_names_the_task(self):
        dashboard.reassign("2026-09-15", LINE, "customers/Widget")
        self.assertEqual(dashboard.measuremoves.entries(self.tmp)[0]["tasks"], ["WID-1"])

    def test_marking_a_line_unbillable_in_place_writes_no_move(self):
        dashboard.reassign("2026-09-15", LINE, "", billable=False)
        self.assertEqual(dashboard.measuremoves.entries(self.tmp), [])

    # ---- moving off the invoice

    def test_a_customer_line_moves_to_dev(self):
        ok, msg = dashboard.reassign("2026-09-15", LINE, "Dev")
        self.assertTrue(ok, msg)
        self.assertEqual(self.find("customers/Widget/portal", "WID-1"), [])
        dev = self.find("Dev")
        self.assertEqual(round(sum(r["hours"] for r in dev), 2), 4.5)

    def test_and_to_an_own_project(self):
        ok, msg = dashboard.reassign("2026-09-15", LINE, "own/MetaAtomic")
        self.assertTrue(ok, msg)
        moved = self.find("own/MetaAtomic")[0]
        self.assertEqual(moved["hours"], 3.0)
        self.assertFalse(moved["billable"])

    def test_and_to_the_customer_node(self):
        # Work for the client that is not on any one project. The node has no fno_code, so
        # it can never produce an enterable line -- which is the point.
        ok, msg = dashboard.reassign("2026-09-15", LINE, "customers/Widget")
        self.assertTrue(ok, msg)
        self.assertEqual(self.find("customers/Widget")[0]["hours"], 3.0)

    def test_the_other_lines_are_untouched(self):
        dashboard.reassign("2026-09-15", LINE, "Dev")
        self.assertEqual(self.find("customers/Widget/portal", "-"), [])
        rest = self.find("customers/Widget/portal")
        self.assertEqual([r["hours"] for r in rest], [1.0])

    def test_the_totals_follow(self):
        dashboard.reassign("2026-09-15", LINE, "Dev")
        text = self.read()
        self.assertIn("**Billable total:** 1.00 h", text)
        self.assertIn("**Internal total:** 4.50 h", text)

    # ---- not for registration, in place

    def test_marking_a_line_unbillable_leaves_it_where_it_is(self):
        ok, msg = dashboard.reassign("2026-09-15", LINE, "", billable=False)
        self.assertTrue(ok, msg)
        row = self.find("customers/Widget/portal", "WID-1")[0]
        self.assertEqual(row["hours"], 3.0)
        self.assertFalse(row["billable"])

    def test_and_says_so_in_the_file(self):
        dashboard.reassign("2026-09-15", LINE, "", billable=False, note="registering time")
        text = self.read()
        self.assertIn("NOT for registration", text)
        self.assertIn("registering time", text)
        self.assertIn("in place", text)

    def test_the_hours_still_count_against_the_client(self):
        dashboard.reassign("2026-09-15", LINE, "", billable=False)
        self.assertEqual(self.find("customers/Widget/portal", "WID-1")[0]["project"],
                         "customers/Widget/portal")
        self.assertIn("**Internal total:** 4.50 h", self.read())

    def test_a_move_and_a_mark_together(self):
        ok, _ = dashboard.reassign("2026-09-15", LINE, "customers/Widget", billable=False)
        self.assertTrue(ok)
        self.assertFalse(self.find("customers/Widget")[0]["billable"])

    # ---- what is refused

    def test_customer_to_customer_is_refused(self):
        ok, msg = dashboard.reassign("2026-09-15", LINE, "customers/Other/thing")
        self.assertFalse(ok)
        self.assertIn("by hand", msg)
        self.assertEqual(self.read(), DAY)

    def test_a_destination_that_is_not_a_place(self):
        for bad in ("../../etc", "customers", "nope/nope", "own"):
            ok, _ = dashboard.reassign("2026-09-15", LINE, bad)
            self.assertFalse(ok, bad)
        self.assertEqual(self.read(), DAY)

    def test_a_line_that_moved_under_the_page(self):
        ok, msg = dashboard.reassign("2026-09-15", dict(LINE, fno_task="GONE"), "Dev")
        self.assertFalse(ok)
        self.assertIn("refresh", msg)

    def test_doing_nothing_is_not_a_write(self):
        ok, _ = dashboard.reassign("2026-09-15", LINE, "")
        self.assertFalse(ok)
        self.assertEqual(self.read(), DAY)

    def test_an_unfinalized_day(self):
        ok, msg = dashboard.reassign("2026-09-16", LINE, "Dev")
        self.assertFalse(ok)
        self.assertIn("close the day", msg)

    # ---- the direction that over-bills is still possible, one line at a time

    def test_dev_onto_a_customer_project_still_works(self):
        dev = {"project": "Dev", "proj_id": "INTERNAL-RND", "activity": "", "fno_task": ""}
        ok, msg = dashboard.reassign("2026-09-15", dev, "customers/Widget/portal")
        self.assertTrue(ok, msg)
        self.assertEqual(round(sum(r["hours"] for r in
                                   self.find("customers/Widget/portal")), 2), 5.5)

    def test_the_file_still_parses_back(self):
        dashboard.reassign("2026-09-15", LINE, "Dev")
        rows = self.rows()
        self.assertEqual(len(rows), 2)
        self.assertEqual(round(sum(r["hours"] for r in rows), 2), 5.5)

    def test_the_files_own_note_survives(self):
        dashboard.reassign("2026-09-15", LINE, "Dev")
        self.assertIn("Reviewed at /log 2026-09-15: nothing to correct.", self.read())


class NotEntered(unittest.TestCase):
    """What the entry page does with a customer line the timesheet says is not billable."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self._root, self._comp = dashboard.ROOT, dashboard.read_companies
        self._rules = dashboard.fno.rules
        dashboard.ROOT = self.tmp
        dashboard.read_companies = lambda: [
            {"firma": "PING", "kunde": "Widget", "key": "widget",
             "projektnr": "230-02", "aktivitet": "", "task_note": ""}]
        dashboard.fno.rules = lambda root=None: {
            "widget": {"customer": "Widget", "firma": "", "proj_id": "", "activity": "",
                       "description": "", "requires": ["task"], "no_charge": False,
                       "path": ""}}

    def tearDown(self):
        dashboard.ROOT, dashboard.read_companies = self._root, self._comp
        dashboard.fno.rules = self._rules
        shutil.rmtree(self.tmp, ignore_errors=True)

    def entry(self, billable):
        e = {"date": "2026-09-15", "project": "customers/Widget/portal", "proj_id": "230-02",
             "activity": "", "fno_task": "", "hours": 3.0, "billable": billable,
             "live": False}
        out = dashboard.collect_entry([e], ["Widget"], "2026-09-21")
        return out["rows"][0], out

    def test_a_billable_line_is_the_customers_company(self):
        row, _ = self.entry(True)
        self.assertEqual(row["firma"], "PING")
        self.assertFalse(row["no_entry"])

    def test_an_unbillable_one_is_grouped_as_not_entered(self):
        row, _ = self.entry(False)
        self.assertTrue(row["no_entry"])
        self.assertEqual(row["firma"], "INTERNAL")

    def test_and_is_never_short_of_anything(self):
        # It is not being typed into F&O, so it cannot be missing what entry requires --
        # the same line billable IS short of the task Widget registers on.
        self.assertEqual([m["field"] for m in self.entry(True)[0]["missing"]], ["fno_task"])
        self.assertEqual(self.entry(False)[0]["missing"], [])
        self.assertEqual(len(self.entry(False)[1]["short"]), 0)

    def test_but_it_keeps_the_customer_and_the_hours(self):
        row, _ = self.entry(False)
        self.assertEqual(row["customer"], "Widget")
        self.assertEqual(row["hours"], 3.0)

    def test_internal_time_is_unaffected(self):
        e = {"date": "2026-09-15", "project": "Dev", "proj_id": "INTERNAL-RND",
             "activity": "", "fno_task": "", "hours": 1.5, "billable": False, "live": False}
        row = dashboard.collect_entry([e], ["Widget"], "2026-09-21")["rows"][0]
        self.assertEqual(row["firma"], "INTERNAL")
        self.assertFalse(row["no_entry"])          # Dev has no customer to book it against


if __name__ == "__main__":
    unittest.main()
